spring.application.name=portfolio
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kakdeprathamesh860@gmail.com
spring.mail.password=gyrxjbizbfyxjkar

spring.mail.properties.mail.smtp.auth=ture
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG